name = "Furniture Brand Reviews"
client_id = "db5beafee602d16825792984fa641886"
application_url = "https://furniturebrandreviews-shopify-app-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "furniture-brand-reviews-dev.myshopify.com"

[access_scopes]
scopes = "read_products,read_themes"

[auth]
redirect_urls = [
  "https://furniturebrandreviews-shopify-app-production.up.railway.app/auth/callback",
  "https://furniturebrandreviews-shopify-app-production.up.railway.app/auth/shopify/callback",
  "https://furniturebrandreviews-shopify-app-production.up.railway.app/api/auth/callback"
]

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = ["customers/data_request"]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  topics = ["customers/redact"]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  topics = ["shop/redact"]
  uri = "/webhooks/shop/redact"

[app_proxy]
url = "https://furniturebrandreviews-shopify-app-production.up.railway.app"
subpath = "fbr"
prefix = "apps"
